var bingoItems = [
    "Encontrar Biggoron",
    "Encontrar Farore's",
    "Arco 'Bowlocked'",
    "'A seed é Jet'",
    "ZL sem ZL",
    "Entrar em Fire sem settar Pierre",
    "Conheceu o vazio de Shadow",
    "Tem uma tunica e não usou",
    "Bk de water em central pillar",
    "Errou a quick kill da gohma",
    "Isolou um check",
    "Pegou a dica de LA",
    "Segunda magia em Shadow",
    "Alguém pediu uma 'Contagem agressiva'",
    "Mais de 50% da call em Live",
    "2 runners em Forest",
    "Item relevante em Tektite grotto",
    "Kakariko village WOTH/Path",
    "Water stone foolish",
    "Bomb bag depois de 1h de seed",
    "Dodongo Foolish",
    "Ad por esporte",
    "Lógica de chaves de spirit",
    "Bottom of the bottom of the well (Map chest)",
    "Bottom of the well Foolish",
    "Tepedino Tutoriais foi mencionado",
    "Mirage tentou aliciar alguem para o Skyward Sword",
    "Algum clipe do GrafitteX foi comentado",
    "CesarMartins12 foi parafraseado",
    "Light mode do gabriel foi lembrado",
    "Sun song pra votlar pra porta",
    "Acabou as Flechas/Bombas",
    "Fez chickens",
    "Dicas do fundo do lago",
    "",
];
