var bingoItems = [
    "Encontrar Biggoron",
    "Encontrar Farore's",
    "Arco 'Bowlocked'",
    "'A seed é Jet'",
    "ZL sem ZL",
    "Entrar em Fire sem settar Pierre",
    "Conheceu o vazio de Shadow",
    "Tem uma tunica e não usou",
    "Bk de water em central pillar",
    "Errou a quick kill da gohma",
    "Isolou um check",
    "pegou a dica de LA",
    "Segunda magia em Shadow",
    "Alguém pediu uma 'Contagem agressiva'",
    "mais de 50% da call em Live",
    "2 runners em Forest",
    "Item relevante em Tektite grotto",
    "Kakariko village WOTH/Path",
    "Water stone foolish",
    "bomb bag depois de 1h de seed",
    "Dodongo Foolish",
    "Ad por esporte",
    "Lógica de chaves de spirit",
    "Bottom of the bottom of the well",
];
